<?php

return [
  'admin_dir' => env('ADMIN_DIR', 'admin'),
  'enable_less_secure_web' => env('CMS_ENABLE_LESS_SECURE_WEB', false),
  'purifier' => [
    'default' => [
      'HTML.Doctype' => 'HTML 4.01 Transitional',
      'HTML.Allowed' => 'div,b,strong,i,em,u,a[href|title|rel|style|target|dofollow|nofollow],ul,ol,li,p[style],br,span[style],img[width|height|alt|src|style|loading],button,ins[style|data-ad-client|data-ad-slot|data-ad-format|data-full-width-responsive],video[src|type|width|height|preload|controls|autoplay|autostart|poster|id|class,muted],meta[name|content|property],link[media|type|rel|href]',
      'HTML.AllowedElements' => [
        'a',
        'b',
        'blockquote',
        'br',
        'code',
        'em',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'hr',
        'i',
        'img',
        'li',
        'ol',
        'p',
        'pre',
        's',
        'span',
        'strong',
        'sub',
        'sup',
        'table',
        'tbody',
        'td',
        'th',
        'thead',
        'tr',
        'u',
        'ul',
        'pre',
        'abbr',
        'kbd',
        'var',
        'samp',
        'hr',
        'iframe',
        'figure',
        'figcaption',
        'section',
        'article',
        'aside',
        'blockquote',
        'caption',
        'del',
        'div',
        'button',
        'ins',
        'video',
        'source',
        'meta',
        'link',
        'audio',
      ],
      'HTML.SafeIframe' => 'true',
      // Add to .env if you want to allow all.
      // CMS_IFRAME_FILTER_URL_REGEX=/^(.*)/
      'URI.SafeIframeRegexp' => env('CMS_IFRAME_FILTER_URL_REGEX', '%^(http://|https://|//)(' . env('CMS_IFRAME_ALLOWED_URLS', 'www.youtube.com/embed/|player.vimeo.com/video/|maps.google.com/maps|www.google.com/maps|docs.google.com/|drive.google.com/|view.officeapps.live.com/op/embed.aspx|onedrive.live.com/embed') . ')%'),
      'Attr.AllowedFrameTargets' => ['_blank'],
      'CSS.AllowedProperties' => [
        'font',
        'font-size',
        'font-weight',
        'font-style',
        'font-family',
        'text-decoration',
        'padding-left',
        'color',
        'background-color',
        'text-align',
        'max-width',
        'border',
        'width',
        'line-height',
        'word-spacing',
        'border-style',
        'list-style-type',
        'border-color',
        'height',
        'min-width',
        'min-height',
        'max-height',
        'list-style',
        'margin',
        'margin-bottom',
        'margin-left',
        'margin-right',
        'margin-top',
        'padding',
        'height',
        'line-height',
        'border-collapse',
      ],
      'CSS.MaxImgLength' => null,
      'AutoFormat.AutoParagraph' => false,
      'AutoFormat.RemoveEmpty' => false,
      'Attr.EnableID' => true,
    ],
    'custom_elements' => [
      ['u', 'Inline', 'Inline', 'Common'],
      ['button', 'Inline', 'Inline', 'Common'],
      ['ins', 'Inline', 'Inline', 'Common'],
      ['meta', 'Inline', 'Empty', 'Common'],
      ['link', 'Inline', 'Empty', 'Common'],
      ['audio', 'Block', 'Optional: (source, Flow) | (Flow, source) | Flow', 'Common'],
    ],
    'custom_attributes' => [
      ['a', 'rel', 'Text'],
      ['a', 'dofollow', 'Bool'],
      ['a', 'nofollow', 'Bool'],
      ['span', 'data-period', 'Text'],
      ['span', 'data-type', 'Text'],
      ['ins', 'data-ad-client', 'Text'],
      ['ins', 'data-ad-slot', 'Text'],
      ['ins', 'data-ad-format', 'Text'],
      ['ins', 'data-ad-full-width-responsive', 'Text'],
      ['img', 'data-src', 'Text'],
      ['img', 'loading', 'Text'],
      ['video', 'autoplay', 'Bool'],
      ['meta', 'name', 'Text'],
      ['meta', 'content', 'Text'],
      ['meta', 'property', 'Text'],
      ['link', 'media', 'Text'],
      ['link', 'type', 'Text'],
      ['link', 'rel', 'Text'],
      ['link', 'href', 'Text'],
      ['link', 'color', 'Text'],
      ['audio', 'controls', 'Bool'],
      ['div', 'data-bs-theme', 'Text'],
      ['button', 'data-bb-toggle', 'Text'],
      ['button', 'data-value', 'Text'],
    ],
  ],

  'date_format' => [
    'date' => 'Y-m-d',
    'date_vn' => 'd-m-Y',
    'date_time' => 'Y-m-d H:i:s'
  ],
];
